### ISSUE TITLE
Navbar & Footer

### ISSUE THREAD

**Issue by soggybag** [noltron000/frosty-website#1]
We talked about the design in person so I'll just be short here. I like your work. 

The large images look good. Might be good to keep the image size as small as possible. 

The nabber could use some attention. It could be a bit taller. The buttons on the right has too much space between them. I feel the black text is not standing out the way you might want it to. Maybe white?

The footer could benefit from it's own design and layout rather than just being a reprise fo the header.

**Comment by noltron000** [comment]
Thanks, should be good now!
