### ISSUE TITLE
I'm not sure this is an h2

### ISSUE THREAD

**Issue by soggybag** [noltron000/frosty-website#3]
https://github.com/noltron000/FEW-1-1_frosty-website/blob/548bb38f7109e066f5f0cd9ebf0e9fa1508effc3/index.html#L37

Just because it is underneath an h1 doesn't mean it's an h2. The h1 seems correct it's the title of a section. What's below this describes the title, it's the not the title of a new sub section. 

Don't make this an h2 just to make the text the next font size smaller. This should probably be p, div, or other tag. Use your style sheet to make it appear at what ever font size you think you need.

**Comment by noltron000** [comment]
Thanks for the advice. You are correct in saying that, as the HTML specification explicitly mentions that headings are not to be used as subtitles for other headings...although I cannot recall the source at which I read this.

This issue has been fixed in a recent commit
