### ISSUE TITLE
id names in css

### ISSUE THREAD

**Issue by soggybag** [noltron000/frosty-website#5]
https://github.com/noltron000/FEW-1-1_frosty-website/blob/548bb38f7109e066f5f0cd9ebf0e9fa1508effc3/css/style.css#L129

While there is nothing wrong with id names in css, I think it's not best practice. Better to use class names. Class names are reusable. Save id names for JavaScript and Navigation. I think in this case I would have assigned the same id name as a class also and styled the class. 

Since ids should only appear once using them for styles tends to encourage you to repeat style rules, where using class names encourages reuse and DRY code.

**Comment by noltron000** [comment]
Agreed, good point!

Would you say that you would _never_ have a css declare a style for an id, then?

**Comment by noltron000** [comment]
Also, issue is fixed in new commit
